spring.application.name=GroupSplitPay
spring.datasource.url=jdbc:postgresql://localhost:5432/jwt_db
spring.datasource.username=postgres
spring.datasource.password=$#@dowStorm#,1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.error.include-message=always

# 256-bit (32+ char) secret, base64 encoded. Generate your own for real projects.
app.jwt.secret=Yz9x8vQwErTyUiOpAsDfGhJkLzXcVbNm3q7w9e1r5t8y2u4i6
app.jwt.expirationms=3600000